const api = [
	['GET', 'orders'],
	['DELETE', 'orders/:id', 'delete_order'],
	['PUT', 'orders/:id', 'update_order'],
	['GET', 'orders/:id', 'get_order'],
	['POST', 'orders', 'create_order'],
	['POST', 'orders/bulk', 'create_order_bulk'],
	['POST', 'orders/delete_all', 'delete_all_orders'],
	['GET', 'orders/bulk_check', 'check_bulk_status'],
	['GET', 'products/:id/market_info', 'product_market_info'],
	['GET', 'products/:id/trade_stats', 'product_trade_stats'],
	['GET', 'products/:id', 'get_product'],
	['GET', 'products'],
	['GET', 'products/recently_viewed', 'recently_viewed_products'],
	['GET', 'products/suggestions', 'product_suggestions'],
	['GET', 'products/:id/average_price_stats', 'average_price_stats'],
	['GET', 'products/:id/depth_of_market_stats', 'orders_table'],
	['GET', 'wallet_transactions'],
	['POST', 'wallet_transactions/add_funds', 'add_funds'],
	['GET', 'current_user'],
	['PUT', 'current_user', 'update_current_user'],
	['POST', 'current_user/logout', 'current_user_logout'],
	['GET', 'current_user/ensure_permissions', 'ensure_permissions'],
	['POST', 'current_user/close_sessions', 'current_user_close_sessions'],
	['POST', 'current_user/confirm_code', 'current_user_confirm_code'],
	['POST', 'current_user/change_email', 'current_user_change_email'],
	['POST', 'current_user/change_phone', 'current_user_change_phone'],
	['POST', 'current_user/change_phone_start', 'current_user_change_phone_start'],
	['POST', 'current_user/change_phone_check_code', 'current_user_change_phone_check_code'],
	['POST', 'current_user/verify_phone', 'current_user_verify_phone'],
	['POST', 'current_user/resend_code', 'current_user_resend_code'],
	['POST', 'current_user/resend_code', 'current_user_resend_code'],
	['POST', 'current_user/resend_second_factor', 'current_user_resend_second_factor'],
	['POST', 'current_user/get_paywin_url', 'current_user_paywin_url'],
	['POST', 'current_user/send_email_confirmation', 'current_user_send_email_confirmation'],
	['POST', 'current_user/confirm_email', 'current_user_confirm_email'],
	['POST', 'current_user/invalidate_token', 'current_user_invalidate_token'],
	['GET', 'region_is_allowed', 'region_is_allowed'],
	['GET', 'geo_info', 'geo_info'],
	['GET', 'current_user/get_binds', 'current_user_get_binds'],
	['POST', 'current_user/bind_create', 'current_user_bind_create'],
	['POST', 'current_user/bind_delete', 'current_user_bind_delete'],
	['POST', 'current_user/bind_game', 'current_user_bind_game'],
	['POST', 'current_user/withdraw', 'current_user_withdraw'],
	['POST', 'current_user/identify', 'current_user_identify'],
	['POST', 'current_user/check_namescan', 'current_user_check_namescan'],
	['POST', 'current_user/check_documents', 'current_user_check_documents'],
	['POST', 'current_user/offer_accept', 'current_user_accept_offer'],
	['POST', 'current_user/offer_decline', 'current_user_decline_offer'],
	['GET', 'current_user/namescan_status', 'current_user_namescan_status'],
	['POST', 'current_user/transfer_accept', 'current_user_transfer_accept'],
	['POST', 'current_user/accept_mbv_terms', 'current_user_accept_mbv_terms'],
	['POST', 'current_user/mbv_migrate', 'current_user_mbv_migrate'],
	['GET', 'current_language', 'current_user_get_language'],
	['POST', 'current_language', 'current_user_change_language'],
	['GET', 'users/:id', 'user'],
	['GET', 'users/:id/feedback', 'user_feedback'],
	['GET', 'users/:id/my_feedback', 'my_feedback'],
	['POST', 'users/:id/my_feedback', 'post_my_feedback'],
	['POST', 'users/notifications_settings', 'notifications_settings_update'],
	['GET', 'notifications', 'get_notifications'],
	['POST', 'notifications/:id/close_notification', 'close_notification'],
	['POST', 'notifications/close_notification_all', 'close_notification_all'],
	['GET', 'notifications/ws_settings', 'notif_ws_settings'],
	['GET', 'messages/:id/get_chat', 'get_chat'],
	['POST', 'messages/:id/send_chat_message', 'send_chat_message'],
	['GET', 'user_inventory'],
	['POST', 'user_inventory/:id/code', 'user_inventory_open_code'],
	['POST', 'user_inventory/:id/close_code', 'user_inventory_close_code'],
	['POST', 'user_inventory/:id/return_code', 'user_inventory_return_code'],
	['POST', 'user_inventory/:id/activate_code', 'user_inventory_activate_code'],
	['POST', 'user_inventory/:id/delete_item', 'user_inventory_delete_item'],
	['GET', 'steam_inventory'],
	['POST', 'user_inventory/:id/check_account', 'check_tokens'],
	['POST', 'user_inventory/:id/send_to_cart', 'send_to_cart'],
	['GET', 'user_inventory/available_by_product', 'check_available_product'],
	['GET', 'order_transactions'],
	['GET', 'order_transactions/:id', 'get_order_transaction'],
	['GET', 'order_transactions/:id/check', 'check_transaction'],
	['GET', 'user_actions'],
	['GET', 'buybooks', 'get_buy_books'],
	['POST', 'buybooks', 'create_buy_books'],
	['POST', 'buybooks/close', 'close_buy_book'],
	['POST', 'buybooks/close_all', 'close_all_buy_book'],
	['GET', 'gifts/:id', 'get_gift'],
	['POST', 'gifts/:id/activate', 'activate_gift'],
	['GET', 'user_tokens'],
	['POST', 'user_tokens/:id/deactivate', 'deactivate_token'],
	['GET', 'platforms'],
	['GET', 'games'],
	['GET', 'games/:id', 'get_game'],
	['POST', 'instant_buy'],
	['POST', 'add_steam_item'],
	['POST', 'add_steam_product'],
	['POST', 'retrieve_steam_item'],
	['GET', 'steam_trade_offer/:id'],
	['POST', 'add_key_product'],
	['POST', 'add_key_item'],
	['POST', 'generate_token'],
	['GET', 'market_stats'],
	['GET', 'face'],
	['GET', 'face/promos', 'promos'],
	['POST', 'subscribe'],
	['GET', 'commissions'],
	['GET', 'settings'],
	['POST', 'send_feedback'],
	['GET', 'partners'],
	['GET', 'cauri_status'],
	['POST', 'cauri_send'],
	['GET', 'withdraw_games'],
	['GET', 'interviews', 'get_active_interview'],
	['GET', 'interviews/available_dates', 'available_dates'],
	['POST', 'interviews', 'create_interview'],
	['POST', 'interviews/cancel', 'cancel_interview'],
	['GET', 'landing/stats', 'gamers_landing_stats'],
	['GET', 'landing/comments', 'gamers_landing_comments'],
	['POST', 'landing/gamers/feedback', 'gamers_landing_request'],
	['GET', 'withdraw_game_invoices/:id', 'withdraw_game_invoice'],
	['GET', 'landing/stats', 'get_developers_stats'],
	['POST', 'landing/partners/feedback', 'send_developers_feedback'],
	['GET', 'faq', 'get_faq_questions'],
	['GET', 'docs/partner_api', 'get_partner_api_content']
];
